# -*- coding: utf-8 -*-
"""GetUrls

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E1d6Ge4tzfgJxOv5JUgXr6pGc0201adY
"""

import requests
from bs4 import BeautifulSoup

def get_links(url):
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")
    links = [link.get("href") for link in soup.find_all("a")]
    return links

def save_links_to_file(links, filename):
    with open(filename, 'a') as file:
        for link in links[:10]:
            print(link, file=file)

def main():
    url = input("Enter Link: ")
    if url.startswith(("https://", "http://")):
        data = requests.get(url)
    else:
        data = requests.get("https://" + url)

    links = get_links(url)
    save_links_to_file(links, "myLinksTam.txt")

if __name__ == "__main__":
    main()

